### ISSUE TITLE
css 2차

### ISSUE THREAD

**Issue by cofla159** [mungtage/frontend#45]
- [x] custom alert
- [x] 매칭 결과 리스트 정렬
- [x] 공고 상세페이지 간격 조정
- [ ] 반응형 작업
- [ ] 공고 상세 모달로 변경
- [ ] 로그인 모달

**Comment by cyberjam** [comment]
@cofla159 따로 custom해서 만들기 보다 [toast 알림](https://www.npmjs.com/package/react-toastify) 가져가 쓰는건 어때요?

![130804494-a9d2d69c-f170-4576-b2e1-0bb7f13dd92d](https://user-images.githubusercontent.com/20448972/198507447-75f14941-72c7-492a-a5c5-aba13a84c127.gif)

**Comment by cofla159** [comment]
@cyberjam 네 그러려구요! custom이라고 쓰긴 했지만 기본 `alert`에서 꾸민다는 생각이었습니다😁
