### ISSUE TITLE
매칭 결과 페이지 스켈레톤 코드 구성

### ISSUE THREAD

**Issue by cofla159** [mungtage/frontend#6]
- [x] 스켈레톤 코드 작성
- [x] 한 사용자 당 동물이 여러 마리일 때의 구성 -> 탭 형식으로 메인페이지에 병합
- [x] 메인페이지 탭 구성

**Comment by cyberjam** [comment]
@cofla159 

어제 디스코드로 ui물어봐주셔서 갑자기 생각이 난게 있습니다.

메인에 실종등록(매칭등록) 탭과 매칭 결과 탭이 있는 ui요.

사용자가 실종등록(매칭등록)을 하지 않은 상태라면 실종등록이 보여지고
한 상태라면 매칭 결과 탭이 보여지도록요.

단 한 유저 당 한 마리를 등록한다고 제한했으면 좋겠습니다

1. ui가 단순해집니다. 
2. 여러마리를 잃어버리는 주인은 특수한 경우이기 때문입니다.
3. 등록했던 강아지를 또 잃어버릴 때 기존에 올린 글을 삭제하고 올릴 수 있도록 한다면 리셋 주기 내 쓸모없는 실종등록글이 삭제 될 수 있겠죠?

채림님께 잘 전달이 되었으려나 모르겠지만 이 부분에 대해 조금 더 함께 의논 하고 싶어요.
필요하다면 피그마로 그려서 보여드릴게요.

**Comment by cyberjam** [comment]
@cofla159 채림님 

- issue탭 안에 있는 milestone<img width="158" alt="image" src="https://user-images.githubusercontent.com/20448972/195422260-342f9e25-a656-42b5-9ce6-06099fa8aee9.png">을 이용하면 due date를 설정하실 수 있습니다. 그러면 대충 언제까지 하시겠구나 저도 알고 스스로도 작성하면서 목표의식이 생기죠 :) 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/20448972/195422904-da0275b7-c1a5-4cc2-a29e-8a8d35eef0ba.png">

- milestone은 issue티켓 보다 상위 개념이라고 생각하면 됩니다. 저 같은 경우 **1개 페이지? 컴퍼넌트?(보기에 쓰읍 이건 좀 하루 이틀로 안되겠는데 싶은 큰 작업단위)에 대한 milestone 1개**를 만들고 그 안에 스켈레톤, 컴퍼넌트 등 작업 및 단계를 나눠 각 issue들을 만듭니다. 위 예시 milestone은 4개 issue에 4개 branch가 만들어지겠군요.

- **1개 issue에 1개 branch**를 만들어 작업하구요. 1개 branch에 커밋할만한게 없다고 느끼실 수도 있습니다. 저도 처음에는 그렇게 느껴졌어요 ㅋㅋ 하지만 요즘 저는 **commit message = 주석**이라 생각합니다. 그러면 이렇게 visual code에서 설명을 볼 수 있거든요. 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/20448972/195424211-a49d656b-b2fd-4ea7-aca3-bfc4f2ee7566.png">

- issue 티켓 만들 때 **development에 branch를 설정**하면 branch가 머지 되었을 경우 함께 close가 되어서 따로 신경쓸 필요없고 편하고 깔끔합니다. 
<img width="320" alt="image" src="https://user-images.githubusercontent.com/20448972/195423784-83f21f32-30e7-4ae6-8937-b5b0ec20e535.png">

- 더불어 issue와 branch에 **Milestone을 설정**해놓으면 머지되었을 경우 작업 퍼센트가 차오르는걸 보실 수 있습니다. 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/20448972/195424341-d465f5d2-dd0e-4963-8e5a-d7218722fcbb.png">

저는 이 부분에서 성취감을 많이 느낍니다. :) 어때요 참 쉽죠? ㅋㅋㅋㅋㅋ 
<img width="496" alt="image" src="https://user-images.githubusercontent.com/20448972/195429434-c78589ae-bdee-42c8-a22e-7675921455b2.png">


이런 방식으로 해! 라고 말하는건 아닙니다. 이런 방식은 어떤지 제안 드려보는 것입니다. 

저는 처음에 이렇게 일하는 방법을 적용 해볼 때 branch를 만들었는데 해당 branch에 커밋을 1개? 2개 밖에 할게 없다고 느꼈습니다. 
요즘은 최대한 작업을 또 세분화하여 암벽등반에서 안전을 위해 후크를 걸듯 커밋을 나눠서 하려고 노력하고 있어요. 
한편으로는 1개 이슈에 많은? 너무 큰 작업들을 넣어두고 branch를 만들어 작업하다가 작업 호흡이 너무 길어져서 성취감을 잃어 늘어지곤 했습니다. 
요즘 저는 조금 빡세게 하고 있어서 1개 issue, 1개 branch 하루이고 1개 milestone은 실제 할 수 있을 기간보다 1일 정도 넉넉 잡는게 마음 놓여서 3일? 길면 4일 잡고 진행하고 있습니다.

제가 이렇게 일하는 건 여러 사람들과 작업하다가 하나씩 터득한 결과이지만 절대적인 건 없다고 생각합니다. 오히려 채림님 방법 중에서도 좋은 것 있다면 듣고 싶고 제가 일하는 방식에 차용하고 싶습니다.

**Comment by cofla159** [comment]
@cyberjam 
안 그래도 이슈가 너무 포괄적으로 구성된 것 같아 고민이었는데 좋은 해답을 주셨네요 :)

그동안 깃헙을 단순 코드 추적용으로만 사용했었는데 진짜 개발자가 일하는 방식을 알려주신 것 같아 좋습니다. 
정성스럽게 사진까지 첨부해서 가이드라인을 만들어 주셔서 저 혼자 보기엔 아깝네요. 내일 회의시간에 다른 팀원분들께도 한 번 공유해드리는 건 어떠세요?

추가로 제가 일하는 방식은 대부분 혼자 일하면서 스스로의 성격에 맞춰진 것들이라 공유드릴만 한 건지 모르겠네요. 무엇이든 받아 적는 그런 거요ㅋㅋ 
갑자기 하나 생각난 건 개발하다가 오류를 만났을 때 해결 과정을 적어놓는 건데요, 재민님도 하고 계시리라 생각되지만 보답으로 제 방식을 소개해드릴게요. 

- 저는 메모장이 항상 띄워져 있기도 하고 자동 저장이라 메모장을 애용합니다. txt파일로 저장하는 메모장 말고 윈도우의 스티커 메모요. 
<img src='https://user-images.githubusercontent.com/70076564/195434366-0972dbf7-025a-4559-9b44-fb115be63eb2.png' width='200px'>

- 주로 한 프로젝트에 스티커메모 한 장을 사용하는데요, 그 프로젝트가 끝나면 블로그에 회고를 적으면서 문제해결 과정을 함께 정리해서 적습니다. 물론 잊어버리기 전에 바로바로 적는 게 좋긴 하지만 저는 몰아서 하는 습관 때문에 그건 어렵더라구요😂 이 과정은 모두 벼락치기를 효과적으로 하기 위한 프로세스입니다.

- 오류를 발견하면 그 상황의 코드와 문제 상황을 적어 놓습니다. 해결하고 나서 적으려고 하면 처음 문제였던 코드가 뭔지 헷갈려서 어렵더라구요. 추가로 위치까지 적어놓아야 사진만 보고 헷갈리지 않습니다.
- 여러 방법을 헤메면서 문제를 해결하는 과정을 모두 적고, 마지막으로 해결에 도움이 된 아하! 할만한 링크를 첨부해둡니다. 글을 혼자 보는 용도로 적다 보니 제가 적은 글 만으로는 부족한 경우가 종종 있더라구요.
<image src='https://user-images.githubusercontent.com/70076564/195434491-fef810e9-498e-48ec-af77-1f7cbc6390d7.png' width='350px'>

- 블로그에 글을 작성하면서 한 이슈를 쓸 때마다 지워나갑니다. 

<br><br>
적고 보니 되게 별거 아니네요. 그냥 흥미로운 킬링타임용 글로 읽어주시면 감사하겠습니다. 
마일스톤과 이슈 연동은 바로 해보겠습니다!

**Comment by newbieJanghan** [comment]
저도 마일스톤 사용하는거 좋아해서 반갑네요! 이번엔 정신 없어서 못썼는데 멘토링 이후에 쭉 일정 관리 들어가보겠습니다
