### ISSUE TITLE
한 사용자가 여러 마리의 동물을 등록하는 이슈

### ISSUE THREAD

**Issue by cofla159** [mungtage/frontend#9]
한 사용자가 한 마리만 업로드 가능하게 할 것인지 여러 마리 가능하게 할 것인지에 대한 논의의 결과가 다음과 같이 나옴.

1. 한 마리로 제한하면 UI적으로나 데이터 중복 면에서 이득을 볼 수 있음(재민)
2. 잃어버린 반려동물을 찾아준다는 목적에서 특정 경우를 배제한다는 게 목적에 부합하지 않는다고 생각함(장한)
3. 확장 가능성으로 남겨두어도 될 듯(프로 버전)
=> 기본 버전은 한 사용자 당 한 마리+등록 데이터는 n일 후 자동 삭제, 프로 버전은 여러 마리 가능+기한은 일 년(?)

그에 따른 task
- [ ] 결과 탭 옆에 "추가 등록" 탭 추가
- [ ] 추가 등록 버튼 클릭 시 프로버전 결제 모달 팝업
- [ ] 결제하기 누르면 로그인 요구 및 로그인 후 결제 페이지 이동

**Comment by cyberjam** [comment]
@cofla159 님
해당 이슈 티켓은 mvp 논의에서 제외한 것으로 알고 있습니다. not planned 상태로 close할까요?

**Comment by cofla159** [comment]
네 제가 닫았습니다~!
